language: php
php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - cd web/vendor
  - php install.php
  - php codecept.phar bootstrap ../dev_tests
  - php codecept.phar -c ../dev_tests

script: php codecept.phar run