language: php
php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - cd web/vendor
  - php install.php
  - php codecept.phar bootstrap
  - cd ../dev_tests
  - php export.php
  - cd ../vendor
  - php codecept.phar run

script: php codecept.phar run