language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - php web/vendor/install.php
  - php web/vendor/codecept.phar bootstrap
  - php web/vendor/codecept.phar build
  - php web/dev_tests/export.php

script: php web/vendor/codecept.phar run