language: php
php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - cd web/vendor
  - php install.php

script:
  - php phpunit.phar --coverage-clover coverage.clover ../dev_tests/unit
  - php ocular.phar code-coverage:upload --access-token="65dc12c9b6b29e90cab660b0fe91064091d641047efdbde1d0a731a8c91a54c5" --format=php-clover coverage.clover