language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - php vendor/install.php
  - php vendor/codecept.phar bootstrap
  - php vendor/codecept.phar build
  - php dev_tests/export.php

script: php vendor/codecept.phar run